# Generated by Django 4.2.23 on 2025-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('RTE', 'Runtime Error'), ('OLE', 'Output Limit Exceeded'), ('IE', 'Internal Error')], default='PE', max_length=3),
        ),
    ]
